version: "3"
services:
  app:
    build:
      context: ./topup
    volumes:
      - ./topup:/topup
    ports:
      - 7030:8000
    depends_on:
      - db
    environment:
      - POSTGRES_USER=topup
      - POSTGRES_PASSWORD=topup
      - POSTGRES_DB=topup
      - POSTGRES_SERVER=db
      - PYTHONPATH=/topup
  db:
    image: postgres:12.4
    ports:
      - "54320:5432"
    expose:
      - "54320"
    restart: always
    environment:
      # if user, pass, and db changes, need to remove previous containers # docker-compose rm -vf
      - POSTGRES_USER=topup
      - POSTGRES_PASSWORD=topup
    volumes:
      - ./db_data:/var/lib/postgresql/data

volumes:
  db_data:

